# Maintainer: jakub.hajek@cometari.com @_jakubhajek
# docker stack deploy -c stack-traefik.yml proxy --with-registry-auth --prune
version: "3.7"

services:
  traefik:
    image: traefik:1.7.12
    command:
      - --api
      - --consul.endpoint=consul-leader:8500
      - --docker.swarmmode
      - --docker.watch
      - --docker.exposedbydefault=false
      - --docker.swarmModeRefreshSeconds=5
      - --metrics
      - --metrics.prometheus
      - --logLevel=ERROR
      - --accessLog
      #- --entrypoints=Name:http Address::80 Redirect.EntryPoint:https
      #- --entrypoints=Name:https Address::443 TLS
      - --defaultentrypoints=http
      #- --defaultentrypoints=http,https
      #- --acme
      #- --acme.email=kuba@cometari.com
      #- --acme.storage=traefik/acme/account
      #- --acme.entryPoint=https
      #- --acme.httpchallenge.entrypoint=http
      #- --acme.httpchallenge
      #- --acme.onhostrule=true
      #- --acme.acmelogging=true
    networks:
      - traefik-consul
      - proxy
    ports:
    - target: 80
      protocol: tcp
      published: 80
      mode: ingress
    - target: 443
      protocol: tcp
      published: 443
      mode: ingress
    - target: 8080
      protocol: tcp
      published: 8080
      mode: ingress
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
      labels:
        - traefik.frontend.rule=Host:traefik.${DOMAIN:-labs.cometari.eu}
        - traefik.enable=true
        - traefik.port=8080
        - traefik.docker.network=proxy
        #admin/admin
        - traefik.frontend.auth.basic.users=admin:$$2y$$05$$1OX5jZ1Kpm/iVKE8tgUhu.STmPkgi0lLxVeP5yEcRioFdV4mcgdTu
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  consul-data-leader-6:
  consul-data-replica-6:

networks:
  proxy:
    driver: overlay
    name: proxy
    attachable: true
  traefik-consul:
    external: true
